### PR TITLE
sync with upstream

### PR DESCRIPTION
**Pull request by marado**
This pulls the two patches from upstream's ranviermud that are still missing on your seanohue's fork.

### CODE REVIEW

**Comment by seanohue** [comment]
I appreciate this, but I rebased the master branch of this fork back to what it was when I forked it over, all of the changes I made are now in a sandbox branch since a lot of them were buggy/broken.

Edit: I think I'll make a development branch for submitting PRs to the main ranviermud project, and merge in some or all of your PRs. Thanks!

**Comment by marado** [comment]
Great. I'm planning to start contributing to this project, so if you plan
on submitting all your changes upstream, I guess I'll either contribute
directly upstream or towards enhancing your PRs.

**Comment by seanohue** [comment]
I'm planning on scrapping most of the stuff I've done on this fork for the time being -- I've learned a lot in the past few months. And I'll contribute meaningful features to the upstream project. I assume that the upstream project's creator/contributors want to focus on features rather than adding content (new rooms, items, classes, enemies, etc.) so if I feel like adding to a playable game, I'll do it in this fork.

That said, if you want to take something that was done in this fork and add it upstream or somehow improve it, then feel free to do so. It's definitely appreciated.

**Comment by seanohue** [comment]
I added contribution guidelines to the README on the master branch of this fork. Thanks again!

**Comment by seanohue** [comment]
@marado  Actually, it looks like upstream is only sporadically maintained. Right now I have this fork up to date with all of my recent pull requests. If there's anything else you want to add to the engine, feel free to submit it here since a lot of PRs have been just sitting there on the upstream repo for weeks/months/years :(

**Comment by marado** [comment]
@seanohue I feel your pain. I wouldn't mind contributing here instead of upstream, if this fork keeps at a better shape (BTW, feel free to cherry-pick https://github.com/shawncplus/ranviermud/pull/50 and https://github.com/shawncplus/ranviermud/pull/52 here, if you want), but I actually am not sure how willing I am to keep working on ranviermud without seeing https://github.com/shawncplus/ranviermud/issues/51 fixed, and I simply think that's a bigger endeavor than I'm willing to commit myself to... I have been looking at ranviermud as an alternative (to me) to https://github.com/marado/TalkerNode , where the benifit would be to be working on something that I wasn't the (almost always) sole contributor of, but that only works for me if the alternative (in this case ranviermud) is structurally sound. The architectural challenge on https://github.com/shawncplus/ranviermud/issues/51 makes me think that, unless it is early avoided, it will grow to be a real pain when scaling up the project...

**Comment by seanohue** [comment]
That's an interesting point, and one that is fixable in a number of ways, and that should be addressed soon. 
Oddly enough, when doing projects at work, I have used an L10n library in a way that is very similar to how it is done in this project, the difference being that if the language is not supported, it will automatically pull the "en" string instead of throwing an error.

Is it possible to just do that?

**Comment by seanohue** [comment]
Also, if we do a complete rewrite of the build mechanism, maybe we should use JSON instead, and use that for the classes/skills as well? I am considering (in the far future) writing a UI tool or CLI tool that will allow non-programmers to easily make new rooms/classes/skills.

**Comment by marado** [comment]
Well, it's really a matter of library design. What you suggest - and I assumed first, from the use ranviermud makes of the lib - would be a library that would take 
`texts={'en':"English sentence",'pt:"same sentence in Portuguese"}` 
texts, while the approach here used is 
`default='en';texts={"original text":{'pt':"text in portuguese"}}`
. I'm not advocating for one or another, I just think that we should use the chosen library as it was designed to (we can switch translation libraries, too, but this approach works well enough).
Notice that, on the current lib approach, if you request `translate("original text","es")` it will return "original text" (the english sentence) since there's no spanish translation (assuming you're using the "let's not throw" flag). 

As for the build mechanism, anything is fine for me, actually. I am partial to JSON (even if not just because it's the most easilly parseable on JS), but I don't mind YML either. Consistency (I mean, same thing for classes and skills too) would be a good decision, tho.

**Comment by seanohue** [comment]
I'm up for using whichever approach will lead to the smallest amount of technical debt/glitches as the project scales.

**Pull request merged**
